### ISSUE TITLE
Add Turkish Q and Turkish F layouts

### ISSUE THREAD

**Issue by hanefff** [aradzie/keybr.com#117]
I learned fast typing on keybr and now I'm willing to improve my both Q and F layout Turkish writing skills. I'd be so happy if I can do it here as well. They are both ISO layouts.

**Comment by aradzie** [comment]
Hi, I added the Turkish language and layouts c27a557f

The change is already live, can you please test it?

I am not sure I got all the rules right, especially about the dotless I, so I am looking for the help of a native speaker.

Also, we have an unfinished Turkish translation, maybe you can [translate](https://github.com/aradzie/keybr.com/blob/master/docs/translations.md) a few hundred words?

**Comment by hanefff** [comment]
Hi, yes I have created it and did some translations, will continue as soon
as I have time.

Thanks a lot for adding the layout! We have two I's, one with dot and one
without dot. They are separate letters and they have their own capital
letters. I can happily test it!

Aliaksandr Radzivanovich ***@***.***>, 8 Nis 2024 Pzt, 17:29
tarihinde şunu yazdı:

**Comment by aradzie** [comment]
FYI, the list of Turkish letters is `"abcçdefgğhıiklmnoöprsştuüvyz"`. I included dotless I, and removed Q, W and X. Is that ok?

**Comment by hanefff** [comment]
We also have "j" , removed ones are correct

**Comment by aradzie** [comment]
Ah, yes, `"J"` is also removed. So the full list of removed letters is `"J"`, `"Q"`, `"W"` and `"X"`.

I took a list of words from [subtitles](https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/40K_Turkish_Subtitles).

The problem is, there is a lot of obscene, vulgar and profane language in subtitles, so it must be censored, and usually I get help from native speakers. However, I managed to do something on my own.

Here is the [dictionary](https://github.com/aradzie/keybr.com-corpus/blob/master/turkish/dict.csv) BEFORE I censored it.

English language is common is subtitles, so I excluded [English words](https://github.com/aradzie/keybr.com-corpus/blob/master/turkish/stoplist-english.txt) from the above list. 

Also, I found a list of [bad words](https://github.com/aradzie/keybr.com-corpus/blob/master/turkish/stoplist-profanity.txt) on the Interned and removed these as well.

The final, censored word list is [here](https://github.com/aradzie/keybr.com/blob/master/packages/keybr-phonetic-model/lib/generate/corpus/words-tr.csv.gz) (it's a gzip archive). Or, for your convenience, the same list as a [spreadsheet](https://docs.google.com/spreadsheets/d/1zLB-iVe1zXVMB2r8x_TKjSS0qjGVBVQzkA6gJWilNDY/edit?usp=sharing). I think it would be a good idea to review the first couple of thousands of words, and if you find anything offensive, just update the spreadsheet and let me know, I'll update the website.

**Comment by hanefff** [comment]
No the opposite actually,  "J" should be added, it wasn't on the list of alphabet you shared.

Sure, I'm checking the list now

**Comment by hanefff** [comment]
Checked first 5500 words, removed half words and would be weird to have ones. You can update update the website

**Comment by aradzie** [comment]
Thanks!

I have updated the dictionary, here is the [difference](https://github.com/aradzie/keybr.com/commit/9d259c556935a983a3a29b02f0b47d56e8b8e1b4#diff-4298248a1fdd36d9b918d1ec8a1d4f9db2fcf2e85abe2e2b6bfa30bf10c389bd). 

The letter `"J"` is also included. Although among the first 3000 words there are only four that have it: `"ajan"`, `"mesaj"`, `"majesteleri"`, `"enerji"`.

I also know why the I letters are not capitalized properly:

```
const a = "AaIıİi";
console.log(a.toUpperCase());           // "AAIIİI", wrong!
console.log(a.toLocaleUpperCase("tr")); // "AAIIİİ", ok!
console.log(a.toLowerCase());           // "aaiıi̇i", wrong!
console.log(a.toLocaleLowerCase("tr")); // "aaııii" ok!
```

I'll fix this issue and update the website tomorrow.
