### ISSUE TITLE
 word "näo" doesn't exist in Portuguese

### ISSUE THREAD

**Issue by LucasRTonin** [aradzie/keybr.com#137]
the correct spelling is "não" which is on the app, also in the app there's "nao" without accents which too doesn't exist in Portuguese language

**Comment by aradzie** [comment]
I took the list of Portuguese words  from [here](https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Portuguese_wordlist), and it includes the word ` "não"`. Unfortunately, almost every such a word list you can find in the Internet if of low quality. That is why I usually build word lists myself. However, I need help from native speakers to remove bad, profane, swearing words because I don't understand the language.

You can help me to improve the Portuguese language in keybr. I could send you a link to a spreadsheet to review and remove inappropriate words. Ping me if you are willing to do this.

Thanks!

**Comment by LucasRTonin** [comment]
Sure i can do that

**Comment by aradzie** [comment]
So, as promised, here is a [spreadsheet](https://docs.google.com/spreadsheets/d/1zM1T5bD2jlf3gK5YH87icO2K1UnJdR5t0X05kZ4LrTA/edit?usp=sharing). It has about 10,000 words that I obtained by scanning the movie subtitles database.

I passed it through a list of bad words that I found on the Internet. However, I don't think that the list is complete so that manual work is still required.

Please review the first 3000 words, remove any bad words, or words like "rape", "murder", etc.

Then I'll update the web site with the final list.

Thanks!

**Comment by LucasRTonin** [comment]
@aradzie reviewed till line 3045, I removed basically words that are used in Portugal but not in Brazil, I also noticed that a lot of very common words are at the end, so the method you used is not accurate to gauge usage, also it seems to be heavily sourced from PT-PT sources, but it shouldn't be a issue, no bad words

**Comment by aradzie** [comment]
@LucasRTonin Thanks! I have  update the website with the updated word list.

You were right, the words came from the European Portuguese. Please excuse my ignorance, I thought the difference between the Brazilian and the European Portuguese is something like the difference between the American and the British English, not too strong to care about.

I hope that now we have a list of words that are common in two languages, so it satisfies everyone.
