### ISSUE TITLE
After deployment on the server, an access error is reported

### ISSUE THREAD

**Issue by lijiaju686** [aradzie/keybr.com#214]
![image](https://github.com/aradzie/keybr.com/assets/97072995/9eae1366-5486-4e67-9837-cee4139b3143)
![image](https://github.com/aradzie/keybr.com/assets/97072995/3be70722-f8f8-45f9-bbfe-0b603717bb2d)
**Go through the tutorial until the end npm start and then directly report an error of 500 when accessing**

**Comment by aradzie** [comment]
Looking at your screenshot, it tries to load the manifest file from `/root/keybr.com/root/...`. Is this intentional, are you the root user in your system? Or is this a configuration error in the `.env` file?

Anyway, check the value of env variable `PUBLIC_DIR`. Mine is `PUBLIC_DIR=~/Projects/keybr.com/root/public`. Make sure that the `${PUBLIC_DIR}/assets/manifest.json` file exists. You may want to run `npm run build-dev` or `npm run watch` to build one.
