### ISSUE TITLE
Bad split of Ukrainian words

### ISSUE THREAD

**Issue by vird** [aradzie/keybr.com#94]
Some words look like parts of words with '. So they were wrongly splitted
ять (пам'ять)
ятаєш (пам'ятаєш)
ятаю (пам'ятаю)
ятай (пам'ятай)
ятаєте (пам'ятаєте)

ємо (e.g. вб'ємо)

язниці (e.g. в'язниці)

обов (обов'язок)
язково (обов'язково)
язку (обов'язку)
пов (пов'язка)

явився (з'явився)
явиться (з'явиться)

other strange words
ден
емі
ем
ім

**Comment by aradzie** [comment]
This bug has been fixed in d54c9f470cf57a0596dbe3d4b472b0b349b1cf35

FIY I keep the development of word frequency dictionaries in a [separate repository](https://github.com/aradzie/keybr.com-corpus/tree/master/lang-uk). There you will find a corpus of Ukrainian text that I cobbled together from a few classic novels.

**Comment by aradzie** [comment]
By the way, we have a Ukrainian translation of the user interface, however it is incomplete. I encourage native speakers to [translate](https://github.com/aradzie/keybr.com/blob/master/docs/translations.md) keybr into your native language. Maybe you can translate a few hundreds of words.
