### ISSUE TITLE
Better German words

### ISSUE THREAD

**Issue by trapicki** [aradzie/keybr.com#99]
While practicing, I encountered the strange non-German word "lhr" (L-H-R). 

The word list is currently 1500 words long, seems to come from https://www.lingq.com/de/deutsch-lernen-online/courses/836064/top-5000-1-6649638/. The original source of the words is unclear and contains words like the notorious "lhr" and "claire", which is a name and for sure not one of the 1500 most frequent words.

1500 covers for sure a good part for a start, but we can improve on that.

A good corpus with lists of words by frequency can be found at 
https://wortschatz.uni-leipzig.de/de
and word lists at 
https://wortschatz.uni-leipzig.de/de/download/German

Hint: They have also word lists for tons of other languages.

**Comment by aradzie** [comment]
Getting a list of common words is a surprisingly tricky problem.

Actually, I took the list of German words from a [movie subtitles database](https://github.com/hermitdave/FrequencyWords). Unfortunately, there are a few problems with this approach:

1. Spelling mistakes, like the words you mentioned.
2. US English specific words, such as person names, etc.
3. Profanity and vulgarity.

I took a look at the corpus that you suggested, and although I don't speak German, I noticed  that some words, like `corona-virus`, are over-represented.

So I took a different route. I downloaded a dozen books from [Project Gutenberg](https://www.gutenberg.org/browse/languages/de), then parsed them to extract a list of words sorted by frequency. Still the result was not ideal. Again, some words, like character names are over-represented. A single novel about Japan can have a lot of Japanese names.

I think I need help from a native speaker. Can you please take a look at this [document](https://docs.google.com/document/d/1cAEpoRd8P8JD1_53qwdPGHKl-ZWOF_0huc3Wpy6kLDc/edit?usp=sharing) and remove the words that you don't like?

**Comment by cunktuskaktus** [comment]
Hello aradzie,

One thing, that I find peculiar...
In German names, nouns and nominalization are capitalized, so is the beginnig of a sentence.
Why give the option to write  german_noun.lower, when it has to be german_noun.title?
 
I am aware that there is a capitalization feature, but unless you put it on 100%, which doesn't feel natural in flow, there will often enough be a german_noun.lower.

It's all about muscle memory, isn't it?

Cheers

**Comment by torbengb** [comment]
I checked your [document](https://docs.google.com/document/d/1cAEpoRd8P8JD1_53qwdPGHKl-ZWOF_0huc3Wpy6kLDc/edit?usp=sharing) and made some minor changes, like removing very weird person names ("Klothilde"?) and some spelling mistakes (new grammar reduces the use of the ß character). 

I notice that some words are capitalized properly but most are not. Is there any pattern to this? Is there a guideline? Should all words be lowercase, or should all words be "proper" case?

**Comment by cunktuskaktus** [comment]
@torbengb I started to capitalize nouns, but then stopped,  it might be superfluous.
Also I ran out of time.

**Comment by torbengb** [comment]
@aradzie I have a feeling that using Guthenberg as a source has the side-effect of getting a corpus of language as it was used a long time ago. In contrast, the corpus from https://wortschatz.uni-leipzig.de/de/download/German as suggested by @trapicki is equally biased toward modern language use, and that's desirable, in my opinion. 

I downloaded the 2023 version of the "news" corpus and ended up with about 30000 words after removing anything containing various non-letter characters. Sure, this still contains names and places, but I feel it's much more representative.

Here are my results: [Google Sheet](https://docs.google.com/spreadsheets/d/1xjRL9vU6Bw3iWc1yYOdCUJRRaZALsvtBYAciFRNTyw4/edit?usp=sharing)

I edited the source file using Notepad++ search and replace (see also [Regex101 results](https://regex101.com/r/JiWSyN/2)):

1. Remove the leading and trailing columns, leaving only the middle column with the word list itself:  
`(\d+\t)*(\t\d+)*`
2. Remove any lines that contain anything besides the actual letters (blank) and any lines that contain consecutive uppercase letters (upper):  
`^(?!([a-zäöüßA-ZÄÖÜ][a-zäöüß]+)$).*`
3. Remove all blank lines:  
Notepad++ > Edit > Line operations > Remove empty lines (containing blank characters)

**Comment by aradzie** [comment]
Finding a good word frequency list is a not an easy task. The ones you can find on the internet are plagued with all kinds of problems:

1. Word lists without frequencies.
2. Word lists too short.
3. Badly formatted word lists (PDF document with pictures).
4. Licensing issues.
5. etc

It might be a good idea to build our own word frequency list by scanning a corpus of German text.

@torbengb, I took a look at your spreadsheet. Unfortunately, you only included words without frequencies. I need word frequencies in order to train the phonetic model which generates pseudo-words. I want the list of common words and the phonetic model to be consistent with each other.

Like you I also tried to scan [Wortschatz Leipcig](https://wortschatz.uni-leipzig.de/de/download/German), I found it to be heavily biased toward modern Internet slang. The `iPhone` word is in the top 200 most frequent words. It is also infested with so many English words and USA company and city names, like Apple, Seattle, etc. 

I found another large corpus of German text, a cleaned up [dump of German Wikipedia](https://github.com/GermanT5/wikipedia2corpus). I think it should provide a more neutral list of words, although this corpus comes with its own set of issues. For example, the `Sowjetunion` word is in the top 1000 most frequent words `\_(ツ)_/`.

I came to realize that any such list must be manually censored.

I moved the development of word frequency lists to a [separate repository](https://github.com/aradzie/keybr.com-corpus). It has a bunch of scripts to scan the texts for most frequent words in different languages. To remove the bad words while scanning we have a few heuristics:

1. An explicit stop list of words to exclude. 
2. Exclude [English words](https://github.com/aradzie/keybr.com-corpus/blob/master/german/stoplist/english.json).
3. Exclude ALL UPPERCASE words
4. Exclude words without vowels
5. Exclude words with punctuation characters (dashes, apostrophes)

To preserve capitalization we count word occurrences in different cases. If the `Kopf` word occurs 10 times as `kopf`, and 100 times as `Kopf`, then we keep the latter.

In the coming days I'll complete my scanning. I think I will combine [Wortschatz Leipcig](https://wortschatz.uni-leipzig.de/de/download/German) as suggested by @trapicki with the Wikipedia dump.

Here is a preview of what I've got so far -- [words-de.csv](https://github.com/aradzie/keybr.com/files/13953678/words-de.csv)

**Comment by torbengb** [comment]
@aradzie  thank you for reviewing my suggestion and for explaining the details you need. I can tell that your [words-de.csv](https://github.com/aradzie/keybr.com/files/13953678/words-de.csv) is already a very very good list, much better than what you started with <3

For what it's worth, I have updated the [Google Sheet](https://docs.google.com/spreadsheets/d/1xjRL9vU6Bw3iWc1yYOdCUJRRaZALsvtBYAciFRNTyw4/edit?usp=sharing) with a **second page including the frequencies.** 

Smart move to have the word lists in a separate repo - I will go check it out! Perhaps I can contribute other languages, too.

**Comment by aradzie** [comment]
@torbengb These are good suggestions, I have updated the corpus project with better word filters.

I've seen your spreadsheet. Where the data is coming from? Can I use this data in keybr as a word frequency list? Or should I proceed with scanning the Wikipedia dump?

**Comment by aradzie** [comment]
One final touch is to pass the resulting list of words through [aspell](http://aspell.net/) to remove all unknown and extraneous words.

So now we have a list of words from a Wikipedia dump:

1. that come from a dictionary
2. with proper frequencies
3. and proper capitalization

I think we can close the issue.

**Comment by aradzie** [comment]
This is just reminder to myself, and to anyone else who is trying to add new languages, that a good corpus of modern, simple, everyday language can be found in the [OpenSubtitles database](https://opus.nlpl.eu/OpenSubtitles/corpus/version/OpenSubtitles). These are available in many spoken languages.

The only caveat is that the corpus must be censored manually, because it contains a lot of profane and vulgar language.

**Comment by geroldmeisinger** [comment]
what about google ngrams? https://github.com/orgtre/google-books-ngram-frequency/tree/main/ngrams

**Comment by trapicki** [comment]
The current corpus of German words is in my experience very good and works fine with the current revision of the software. I  reset my stats on a regular basis to start from scratch (keybr.com is great in that regards, takes only 5-6 minutes to get me to my perfect training spot), thus I have a very good impression of the words that come up.

Due to the algorithm to only use characters that are already unlocked, only some training sessions are difficult to populate with matching words, like J, Y and Q (fortunately U is more frequenty as Q, as Q in nearly all cases is followed by a U). In this cases, it falls back to ngram word generation, which is perfectly ok. As soon as more letters are unlocked and you come back to train that letter, usually sensible words with that letter are available.

As the OP, I'd say, for now German is perfectly fine.

If we need improvement, I'd suggest the corpus from monkeytype, which has 200.000+ words that where sifted for unpleasant words and names.
